name: huyphan_app
description: "A new Flutter project."
publish_to: 'none' # Ngăn publish nhầm lên pub.dev
version: 1.0.0+1

environment:
  sdk: '^3.10.4'

dependencies: 
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_easyloading: ^3.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  image_picker: ^1.0.7
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  badges: ^3.1.2
  
  

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  # Bạn có thể thêm config splash ở đây nếu cần
  color: "#00acc1"
  image: "assets/images/app_icon.png"