name: huyphan_app
description: "A new Flutter project."
publish_to: 'none' # Ngăn publish nhầm lên pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2       # Chọn ảnh từ gallery/camera
  http: ^1.2.2               # Gọi API
  #mobile_scanner: ^3.5.6     # Quét QR/Barcode (dùng cho tab Quét QR sau này)

  # THÊM 2 PACKAGE QUAN TRỌNG CHO CHỨC NĂNG CẬP NHẬT QR
  flutter_easyloading: ^3.0.5   # Loading đẹp khi gọi API
  qr_flutter: ^4.1.0 
  mobile_scanner: ^5.1.1           # Tạo và hiển thị mã QR chuẩn quốc tế (rất quan trọng!)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/   # Tất cả ảnh trong thư mục này đều được load

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"   # Đảm bảo file này tồn tại và là 1024x1024