name: huyphan_app
description: "A new Flutter project."

# Ngăn publish nhầm lên pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2      # Package chọn ảnh từ gallery/camera
  http: ^1.2.2              # Package thực hiện HTTP requests (GET, POST, ...)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Thêm thư mục assets
  assets:
    - assets/images/

  # Ví dụ thêm từng file cụ thể (bỏ comment nếu cần)
  # assets:
  #   - assets/images/a_dot_burr.jpeg
  #   - assets/images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic