name: huyphan_app
description: "A new Flutter project."
publish_to: 'none' # Ngăn publish nhầm lên pub.dev
version: 1.0.0+1

environment:
  sdk: '^3.10.4'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_easyloading: ^3.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  # Bạn có thể thêm config splash ở đây nếu cần
  color: "#00acc1"
  image: "assets/images/app_icon.png"